static void bstack(Monitor *m);
static void bstackhoriz(Monitor *m);
static void centeredfloatingmaster(Monitor *m);
static void centeredmaster(Monitor *m);
static void deck(Monitor *m);
static void dwindle(Monitor *mon);
static void fibonacci(Monitor *mon, int s);
static void monocle(Monitor *m);
static void spiral(Monitor *mon);
static void tile(Monitor *);
